

select *
from sys.objects o  
where name in(
'tPLDmatrizEvaluacionesRiesgo'
,'tPLDmatrizEvaluacionesRiesgoCalificaciones'
,'tPLDmatrizEvaluacionesRiesgoCalificacionesAgrupadas'
,'tPLDmatrizEvaluacionesRiesgoCalificacionesFinales'
,'tPLDmatrizConfiguracionEdades'
,'tPLDmatrizConfiguracionGenero'
,'tPLDmatrizConfiguracionGeografia'
,'tPLDmatrizConfiguracionIngresos'
,'tPLDmatrizConfiguracionInstrumentos'
,'tPLDmatrizConfiguracionListas'
,'tPLDmatrizConfiguracionNivelesRiesgo'
,'tPLDmatrizConfiguracionPonderaciones'
,'tPLDmatrizConfiguracionProductosServicios'
,'tPLDmatrizConfiguracionTipoSocio'
,'tPLDmatrizConfiguracionTransaccionalidad'
,'tPLDmatrizConfiguracionSucursales'
,'tPLDmatrizConfiguracionActividad'
,'tPLDcatalogoInusualidades'
,'tPLDmatrizConfiguracionOcupaciones'
,'tPLDmatrizConfiguracionTransaccionalidadNumeroOperaciones'
,'IX_tSDOtransaccionesFinancieras_INC_IdOperacion_IdCuenta'
,'trAlertasOficialCumplimiento'
,'tPLDmatrizConfiguracionOrigenDestinoRecursos'
,'Parametro Modulo'
,'vPLDusuariosLogin'
,'fnPLDmatrizEvaluacionEdades'
,'fnPLDobtenerUltimoPerfilSocios'
,'fnPLDultimaEvaluacionPorSocio'
,'fnPLDemailsCCC'
,'fnPLDorigenesRecursosSocios'
,'fnPLDdestinosRecursosSocios'
,'pPLDevaluacionDeRiesgo'
,'pCnPLDmatrizEvaluacionNivelDeRiesgo'
,'pCTLpermisosPorPerfilPorUsuario'
,'pPLDf3'
,'pPLDdeteccionInusualidades'
,'pCnPLDoperacionesMetodoPago'
,'pPLDevaluacionDeRiesgoDesdeErprise'
,'pActualizacionNivelRiesgoSociosDesdeUltimaEvaluacion'
,'pPLDdeterminarNivelRiesgoSocio')

