
/*

SOCIO - EDAD 
SOCIO - TIPO SOCIO 
SOCIO - GÉNERO 
SOCIO - SUCURSAL
GEOGRAFÍA - ENTIDAD DE NACIMIENTO
GEOGRAFÍA - MUNICIPIO DE RESIDENCIA
GEOGRAFÍA - MUNICIPIO SUCURSAL
LISTAS Y TERCEROS - PROPIETARIO REAL
LISTAS Y TERCEROS - PROVEEDOR DE RECURSOS
LISTAS Y TERCEROS - PEP
LISTAS Y TERCEROS - LISTA BLOQUEADA
INGRESOS - SUELDO RANGO PF
INGRESOS - SUELDO RANGO PM
INGRESOS - OCUPACION
TRANSACCIONALIDAD DECLARADA - DEPOSITOS DECLARADOS DE MENORES
TRANSACCIONALIDAD DECLARADA - RETIROS DECLARADOS DE MENORES
TRANSACCIONALIDAD DECLARADA - DEPOSITOS DECLARADOS DE MAYORES
TRANSACCIONALIDAD DECLARADA - RETIROS DECLARADOS DE MAYORES
TRANSACCIONALIDAD DECLARADA - DEPOSITOS DECLARADOS DE MORALES
TRANSACCIONALIDAD DECLARADA - RETIROS DECLARADOS DE MORALES
TRANSACCIONALIDAD - DEPOSITOS DE MENORES
TRANSACCIONALIDAD - RETIROS DE MENORES
TRANSACCIONALIDAD - DEPOSITOS DE MAYORES
TRANSACCIONALIDAD - RETIROS DE MAYORES
TRANSACCIONALIDAD - DEPOSITOS DE MORALES
TRANSACCIONALIDAD - RETIROS DE MORALES
PRODUCTOS Y SERVICIOS - SERVICIOS
PRODUCTOS Y SERVICIOS - PRODUCTOS
PRODUCTOS Y SERVICIOS - CANALES DE DISTRIBUCIÓN

*/

-- 23153

