
-- TRUNCATE TABLE dbo.tBURcatalogosScoreBuroTarjetaCredito

INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('131','Alta utilización del límite de crédito.') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('132','Poco historial de crédito.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('133','Poco historial de crédito.') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('134','Poco historial de crédito.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('135','Poca solvencia en tarjetas de crédito')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('136','Alta exposición en tarjetas de crédito') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('137','Sin Información reciente sobre consultas')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('138','Se observa morosidades bastante recientes en el histórico de las cuentas.') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('139','Se observa morosidades bastante recientes en el histórico de las cuentas.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('140','Se aperturaron varias cuentas de tarjetas de crédito recientemente.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('141','Se observan pagos vencidos en los últimos dos años.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('142','Varias cuentas de tarjeta de crédito abiertas') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('143','Se observan préstamos personales recientemente abiertos')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('144','Se observan cuentas de tarjeta de crédito con utilizaciones altas.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('145','Se alcanzó la peor morosidad de una tarjeta de crédito recientemente.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('146','Poco historial de crédito.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('147','Poco historial de crédito.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('148','Poco historial de crédito.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('149','Montos por pagar más altos que el promedio del portafolio en tarjeta de crédito.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('150','Se observan más de dos pagos vencidos en los últimos 6 meses.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('151','Se observan préstamos personales con altos saldos.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('152','Altos porcentajes de cuentas en un pago vencido.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('153','Altos porcentajes de cuentas en un pago vencido.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('154','Se observa un porcentaje de cuentas con dos pagos vencidos')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('155','Se observan cuentas con saldo altos y desactualizadas')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('156','Se observan muchas cuentas de telecomunicaciones abiertas recientemente')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('157','Se observa en el histórico de pagos altas morosidades recientes.') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('158','Se observa en el histórico de pagos altas morosidades recientes.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('159','Alta exposición en cuentas de tarjetas de crédito.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('160','Alto número de veces que el Cliente se acercó o alcanzó su peor morosidad.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('161','Se observa un correcto manejo de cuentas.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('162','Se observa un correcto manejo de cuentas.')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('163','Se observa una exposición moderada en cuentas de tarjeta de crédito') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('164','Alguna cuenta llegó a un pago vencido') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('165','Alguna cuenta llegó a dos pagos vencidos') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('166','Alguna cuenta alcanzó dos pagos vencidos y el cliente alcanzó alta exposición') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('167','Alguna cuenta está a punto de llegar a castigo')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('171','Cuentas con morosidad de 90 días o más') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('172','Morosidad reciente') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('173','Sin cuentas') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('174','Proporción de cuentas al corriente respecto de cuentas totales muy baja') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('175','Sin cuentas') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('176','Sin cuentas al corriente') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('177','Pocas cuentas al corriente') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('178','Sin cuentas de créditos hipotecarios') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('179','Sin cuentas de créditos hipotecarios al corriente')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('180','Varias cuentas a plazos con monto de crédito bajo') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('181','Varias cuentas a plazos de préstamos personales') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('182','Sin cuentas de créditos automotrices') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('183','Muchas cuentas revolventes bancarias abiertas recientemente con saldos')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('184','Sin cuentas') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('185','Sin cuentas abiertas con saldos cero') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('186','Sin cuentas abiertas') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('187','Promedio de antigüedad de cuentas bajo') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('188','Sin cuentas bancarias revolventes actualizadas recientemente') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('189','Proporción alta de saldo en cuentas bancarias revolventes, actualizadas recientemente respecto al límite de crédito') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('190','Varias cuentas bancarias revolventes con alto porcentaje de utilización')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('191','Varias cuentas con alto porcentaje de utilización') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('192','Morosidad reciente') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('193','Sin cuentas') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('194','Proporción de cuentas al corriente respecto de cuentas totales muy baja') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('195','Sin cuentas de crédito microfinanciero')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('196','Sin cuentas de crédito microfinanciero al corriente') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('197','Pocas cuentas de crédito microfinanciero al corriente') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('198','Sin cuentas bancarias revolventes')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('199','Pocas cuentas bancarias revolventes')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('200','Varias cuentas a plazos de préstamos personales') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('201','Sin cuentas de créditos automotrices')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('202','Varias cuentas abiertas recientemente')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('203','Sin cuentas')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('204','Sin cuentas abiertas con saldo de cero')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('205','Sin cuentas abiertas')   
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('206','Poca antigüedad crediticia')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('207','Sin cuentas con monto de crédito mayor a cero, actualizadas recientemente') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('208','Monto del crédito total bajo en cuentas actualizadas recientemente') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('209','Proporción alta de saldo en cuentas bancarias revolventes actualizadas recientemente respecto al límite de crédito') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('210','Varias cuentas con alto porcentaje de utilización') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('211','Sin cuentas')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('212','Cuentas con morosidad de 90 días o más') 
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('213','Varias cuentas con morosidad reciente')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('214','Sin cuentas')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('215','Proporción baja de cuentas al corriente respecto de cuentas totales')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('216','Sin cuentas')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('217','Sin cuentas al corriente')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('218','Sin cuentas de crédito microfinanciero')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('219','Sin cuentas de crédito microfinanciero al corriente')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('220','Sin cuentas revolventes')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('221','Sin cuentas revolventes al corriente')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('222','Pocas cuentas revolventes al corriente')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('223','Sin cuentas de crédito hipotecario')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('224','Sin cuentas de créditos automotrices')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('225','Varias cuentas de préstamos personales a plazos')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('226','Sin cuentas')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('227','Sin cuentas abiertas con saldo cero')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('228','Pocas cuentas abiertas con saldo cero')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('229','Sin información de cuentas abiertas')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('230','La cuenta más antigua es muy reciente')  
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion)
VALUES ('231','Proporción alta de saldo en cuentas revolventes actualizadas recientemente respecto al límite de crédito')
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion,EsRazon,EsExclusion)
VALUES ('-001','Consumidor fallecido.',0,1)
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion,EsRazon,EsExclusion)
VALUES ('-005','Un archivo de crédito donde todas las cuentas están actualmente cerradas y por lo menos una cuenta con más de 90 días o más de morosidad. MOP ≥ 04.',0,1)
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion,EsRazon,EsExclusion)
VALUES ('-006','Un archivo de crédito donde todas las cuentas han sido abiertas en los últimos 6 meses y por lo menos  una cuenta con más de 60 días o más de morosidad MOP ≥ 03.',0,1)
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion,EsRazon,EsExclusion)
VALUES ('-007','Un archivo de crédito donde todas las cuentas han sido abiertas en los últimos 6 meses y por lo menos una cuenta tiene 30 días o más de morosidad. MOP ≥ 02.',0,1)
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion,EsRazon,EsExclusion)
VALUES ('-008','El archivo de crédito no tiene por lo menos una cuenta actualizada en los últimos 12 meses o por lo que menos una cuenta abierta en los últimos 6 meses ("Criterios mínimos de calificación").',0,1)
INSERT INTO dbo.tBURcatalogosScoreBuroTarjetaCredito(Codigo,Descripcion,EsRazon,EsExclusion)
VALUES ('-009','El archivo de crédito no tiene cuentas para calcular el Score.',0,1) 



SELECT * FROM dbo.tBURcatalogosScoreBuroTarjetaCredito
