
TRUNCATE TABLE dbo.tBURcatalogosCodigosPaisesMonedas

INSERT INTO dbo.tBURcatalogosCodigosPaisesMonedas (Id,Codigo,Pais)
VALUES
(1,'AF','Afganistán'), 
(2,'AL','Albania'), 
(3,'DE','Alemania'), 
(4,'AD','Andorra'), 
(5,'AO','Angola'), 
(6,'AI','Anguila'), 
(7,'AQ','Antártida'), 
(8,'AG','Antigua y Barbuda'), 
(9,'SA','Arabia Saudita'), 
(10,'DZ','Argelia'), 
(11,'AR','Argentina'), 
(12,'AM','Armenia'), 
(13,'AW','Aruba'), 
(14,'AU','Australia'), 
(15,'AT','Austria'), 
(16,'AZ','Azerbaiyán'), 
(17,'BS','Bahamas'), 
(18,'BH','Bareín'), 
(19,'BD','Bangladés'), 
(20,'BB','Barbados'), 
(21,'BE','Bélgica'), 
(22,'BZ','Belice'), 
(23,'BJ','Benin'), 
(24,'BM','Bermudas'), 
(25,'BY','Bielorrusia'), 
(26,'BO','Bolivia, Estado Plurinacional de'), 
(27,'BQ','Bonaire, San Eustaquio y Saba'), 
(28,'BA','Bosnia y Herzegovina'), 
(29,'BW','Botsuana'), 
(30,'BR','Brasil'), 
(31,'BN','Brunéi Darussalam'), 
(32,'BG','Bulgaria'), 
(33,'BF','Burkina Faso'),
(34,'BI','Burundi'), 
(35,'BT','Bután'), 
(36,'CV','Cabo Verde'), 
(37,'KH','Camboya'), 
(38,'CM','Camerún'), 
(39,'CA','Canadá'), 
(40,'CL','Chile'), 
(41,'CN','China'), 
(42,'CY','Chipre'), 
(43,'CO','Colombia'), 
(44,'CI','Costa de Marfil'),  
(45,'CR','Costa Rica'), 
(46,'HR','Croacia'), 
(47,'CU','Cuba'), 
(48,'CW','Curaçao'), 
(49,'DK','Dinamarca'),
(50,'DJ','Yibuti'), 
(51,'DM','Dominica'), 
(52,'EC','Ecuador'), 
(53,'EG','Egipto'), 
(54,'SV','El Salvador'), 
(55,'ER','Eritrea'), 
(56,'SK','Eslovaquia'), 
(57,'SI','Eslovenia'), 
(58,'ES','España'), 
(59,'US','Estados Unidos'), 
(60,'EE','Estonia'), 
(61,'ET','Ethiopia'), 
(62,'FJ','Fiji'), 
(63,'PH','Filipinas'),  
(64,'FI','Finlandia'), 
(65,'FR','Francia'), 
(66,'GA','Gabón'), 
(67,'GM','Gambia'),  
(68,'GS','Georgia del sur y las islas sandwich'),  
(69,'GH','Ghana'), 
(70,'GI','Gibraltar'), 
(71,'GD','Granada'), 
(72,'GR','Grecia'), 
(73,'GL','Groenlandia'), 
(74,'GP','Guadalupe'), 
(75,'GU','Guam'), 
(76,'GT','Guatemala'), 
(77,'GY','Guayana'), 
(78,'GF','Guayana Francesa'), 
(79,'GG','Guernsey'), 
(80,'GN','Guinea-Bisáu'), 
(81,'GQ','Guinea Ecuatorial'), 
(82,'GW','Guinea-Bissau'), 
(83,'HT','Haití'), 
(84,'HN','Honduras'), 
(85,'HK','Hong Kong'), 
(86,'HU','Hungría'), 
(87,'IN','India'), 
(88,'ID','Indonesia'), 
(89,'IQ','Irak'), 
(90,'IR','Irán'), 
(91,'IE','Irlanda'), 
(92,'BV','Isla Bouvet'), 
(93,'IM','Isla de Man'), 
(94,'CX','Isla de Navidad'), 
(95,'HM','Isla Heard e Islas McDonald'), 
(96,'NF','Isla Norfolk'), 
(97,'IS','Islandia'), 
(98,'AX','Islas Åland'),
(99,'KY','Islas Caimán'),  
(100,'CK','Islas Cook'),  
(101,'FK','Islas Malvinas (Falkland),'), 
(102,'FO','Islas Faroe'),  
(103,'MP','Islas Marianas del Norte'), 
(104,'MH','Islas Marshall (las),'), 
(105,'PN','Islas Pitcairn'), 
(106,'RE','Islas Reunión'), 
(107,'SB','Islas Salomón (las),'), 
(108,'VI','Islas Vírgenes (EE.UU.), '),
(109,'VG','Islas Vírgenes Birtánicas'), 
(110,'IL','Israel'), 
(111,'IT','Italia'), 
(112,'JM','Jamaica'), 
(113,'JP','Japón'), 
(114,'JE','Jersey'), 
(115,'JO','Jordania'),
(116,'QA','Catar'), 
(117,'KZ','Kazajistán'), 
(118,'KE','Kenia'), 
(119,'KG','Kirguistán'), 
(120,'KI','Kiribatí'), 
(121,'KW','Kuwait'), 
(122,'SY','La República Árabe de Siria'), 
(123,'KR','La República de Corea del Sur'), 
(124,'CD','República Democrática del Congo'), 
(125,'KP','Corea del Norte'), 
(126,'LA','República Democrática Popular Lao'), 
(127,'UM','Islas de Ultramar Menores de EEUU'), 
(128,'TC','Las Islas Turcas y Caicos'), 
(129,'LS','Lesoto'), 
(130,'LV','Letonia'), 
(131,'LB','Líbano'), 
(132,'LR','Liberia'), 
(133,'LY','Libia'), 
(134,'LI','Liechtenstein'), 
(135,'LT','Lituania'), 
(136,'AE','Los Emiratos Árabes Unidos'), 
(137,'NL','Los Países Bajos'),  
(138,'LU','Luxemburgo'), 
(139,'MO','Macao'), 
(140,'MK','Macedonia'),  
(141,'MG','Madagascar'), 
(142,'MY','Malasia'), 
(143,'MW','Malaui'), 
(144,'MV','Maldivias'), 
(145,'ML','Mali'), 
(146,'MT','Malta'), 
(147,'MA','Marruecos'), 
(148,'MQ','Martinica'), 
(149,'MU','Mauricio'), 
(150,'MR','Mauritania'), 
(151,'YT','Mayotte'), 
(152,'MX','México'), 
(153,'FM','Micronesia'),  
(154,'MD','República de Moldavia'), 
(155,'MC','Mónaco'), 
(156,'MN','Mongolia'), 
(157,'ME','Montenegro'), 
(158,'MS','Montserrat'), 
(159,'MZ','Mozambique'), 
(160,'NA','Namibia'), 
(161,'NR','Nauru'), 
(162,'NP','Nepal'), 
(163,'NI','Nicaragua'), 
(164,'NE','Níger'), 
(165,'NG','Nigeria'), 
(166,'NU','Niue'), 
(167,'NO','Noruega'), 
(168,'NC','Nueva Caledonia'), 
(169,'NZ','Nueva Zelandia'), 
(170,'OM','Omán'), 
(171,'PK','Pakistán'), 
(172,'PW','Palaos'), 
(173,'PS','Palestina, Estado de'), 
(174,'PA','Panamá'), 
(175,'PG','Papua Nueva Guinea'), 
(176,'PY','Paraguay'), 
(177,'PE','Perú'), 
(178,'PF','Polinesia Francesa'), 
(179,'PL','Polonia'), 
(180,'PT','Portugal'), 
(181,'PR','Puerto Rico'), 
(182,'GB','Reino Unido'), 
(183,'CF','República Centro Africana'), 
(184,'CZ','República Checa'), 
(185,'GE','Georgia'), 
(186,'MM','Birmania (o Myanmar),'), 
(187,'TD','Chad'), 
(188,'CG','Congo'), 
(189,'ST','Santo Tomé y Príncipe'), 
(190,'TL','Rep. Democrática de Timor Oriental'), 
(191,'DO','República Dominicana'),  
(192,'TZ','Tanzania, República Unida de'), 
(193,'RW','Ruanda'), 
(194,'RO','Rumania'), 
(195,'RU','Rusia'), 
(196,'EH','Sahara Occidental'), 
(197,'AS','Samoa Americana'), 
(198,'WS','Samoa'), 
(199,'BL','San Bartolomé'), 
(200,'KN','San Cristóbal y Nieves'), 
(201,'SM','San Marino'), 
(202,'MF','San Martín (parte francesa),'), 
(203,'PM','San Pedro y Miquelón'),
(204,'VC','San Vicente y las Granadinas'), 
(205,'SH','Santa Helena, Ascensión y Tristán'),  
(206,'LC','Santa Lucía'), 
(207,'SN','Senegal'),  
(208,'RS','Serbia'), 
(209,'SC','Seychelles'), 
(210,'SL','Sierra Leona'), 
(211,'SG','Singapur'), 
(212,'SX','Sint Maarten (parte holandesa),'), 
(213,'SO','Somalia'), 
(214,'LK','Sri Lanka'),
(215,'ZA','Sudáfrica'), 
(216,'SD','Sudán del Norte'), 
(217,'SS','República de Sudán del Sur'), 
(218,'SE','Suecia'), 
(219,'CH','Suiza'), 
(220,'SR','Surinam'), 
(221,'SJ','Svalbard y Jan Mayen'), 
(222,'SZ','Swazilandia'), 
(223,'TH','Tailandia'), 
(224,'TW','Taiwán (Provincia de China),'), 
(225,'TJ','Tayikistán'), 
(226,'IO','Territorio Británico Océano Índico'), 
(227,'CC','Territorio de las Islas Cocos'),  
(228,'TF','Territorios Australes Franceses'),  
(229,'TG','Togo'), 
(230,'TK','Tokelau'), 
(231,'TO','Tonga'), 
(232,'TT','Trinidad y Tobago'), 
(233,'TN','Túnez'), 
(234,'TM','Turkmenistán'), 
(235,'TR','Turquía'), 
(236,'TV','Tuvalu'), 
(237,'UA','Ucrania'), 
(238,'UG','Uganda'), 
(239,'KM','Unión de las Comoras'),  
(240,'UY','Uruguay'), 
(241,'UZ','Uzbekistán'), 
(242,'VU','Vanuatu'), 
(243,'VA','Ciudad del Vaticano'), 
(244,'VE','Venezuela'), 
(245,'VN','Viet Nam'), 
(246,'WF','Wallis y Futuna'), 
(247,'YE','Yemen'), 
(248,'ZM','Zambia'), 
(249,'ZW','Zimbabue') 
 
 
 SELECT * FROM dbo.tBURcatalogosCodigosPaisesMonedas