
-- 
TRUNCATE TABLE tBURcatalogosCodigosIndiceCapacidadCrediticiaICC
GO


INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('010','Cuenta con histórico de pagos reciente.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('011','Cuentas reportadas con morosidad.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('012','Límite de crédito disponible en cuentas revolventes.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('013','Cuentas con alto endeudamiento.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('015','Cuentas con endeudamiento en cobranza.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('016','Cuentas con endeudamiento en morosidad.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('017','Cuentas de reciente apertura con alto endeudamiento.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('019','Cuentas de reciente apertura con empresas de crédito al consumo con alto endeudamiento.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('020','Cuentas de reciente apertura con tiendas departamentales con alto endeudamiento.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('021','Cuentas de reciente apertura revolventes con alto endeudamiento.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('022','Cuentas de reciente apertura compañías financieras con alto endeudamiento.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('023','Cuentas departamentales con endeudamiento.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('024','Cuentas revolventes con endeudamiento.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('025','Cuentas revolventes con alto endeudamiento.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('026','Cuentas con saldo vencido.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('040','Reporte de bancarrota.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('041','Fecha de la última consulta es reciente.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('042','Cuentas con morosidad.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('043','Cuentas de reciente apertura con morosidad.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('044','Registro en cobranza o con reporte negativa.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('045','Frecuencia de morosidad.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('046','Nivel de morosidad en las cuentas.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('047','Alta morosidad.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('048','Registro reportado con alta morosidad o en cobranza.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('050','Información demográfica.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('051','Información demográfica faltante. ')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('052','Número de consultas.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('053','Frecuencia de las consultas al expediente.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('054','Cuenta reciente con poca información.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('055','Registro negativo con endeudamiento.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('056','Proporción del saldo al límite de crédito de las cuentas.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('060','Histórico de pago insuficiente.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('061','Cuentas recientes con poca información.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('062','Cuentas revolventes recientes con poca información.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('063','Préstamo bancario automotriz reciente con poca información.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('064','Préstamo no bancario automotriz reciente con poca información.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('066','Préstamo de empresas de crédito al consume reciente con poca información.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('067','Préstamo reciente con poca información.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('068','Préstamo hipotecario reciente con poca información.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('069','Préstamo no hipotecario reciente con poca información.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('070','Cuenta departamental reciente con poca información.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('071','Cuenta revolvente reciente con poca información.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('072','No existe préstamo hipotecario reportado.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('074','No existe información reciente del saldo de préstamo no hipotecario.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('075','No hay saldos recientes en cuentNO departamentales.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('076','No hay saldos recientes en cuentaNOrevolventes.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('100','Periodo de tiempo de las cuentas ha sido establecido.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('101','Periodo de tiempo de las cuentas automotrices  ha sido establecido.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('103','Periodo de tiempo de las cuentas de crédito al consumo ha sido establecido.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('104','Periodo de tiempo de los prestamos ha sido establecido.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('105','Periodo de tiempo de los créditos hipotecarios reportados ha sido establecido.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('106','Periodo de tiempo de los préstamos abiertos ha sido establecido.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('107','Periodo de tiempo de las cuentas departamentales ha sido establecido.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('108','Periodo de tiempo de las cuentas revolventes ha sido establecido.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('109','Cuenta inactiva por un periodo largo de tiempo.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('110','Tiempo desde que se presentó morosidad es reciente o desconocido.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('111','Tiempo desde que se reportó un registro negativo o en cobranza es reciente.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('112','Tiempo desde que la última cuenta fue aperturada es reciente.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('113','Tiempo desde que la última cuenta automotriz fue aperturada es reciente.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('115','Tiempo desde que la última cuenta de crédito al consumo fue aperturada es reciente.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('116','Tiempo desde que el último préstamo fue aperturado es reciente.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('117','Tiempo desde que la última cuenta departamental fue establecida.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('118','Tiempo desde que la última cuenta revolvente fue establecida.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('130','Número de cuentas actualmente con morosidad.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('131','Número de cuentas con morosidad.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('132','Número de cuentas con morosidad reciente.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('134','Número de cuentas departamentales abiertas.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('135','Número de registros negativos.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('139','Número de registros en cobranza.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('140','Número de cuentas de crédito al consumo registradas en relación al periodo de historia de créditos al consumo.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('141','Número de consultas de empresas de crédito al consume.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('142','Número de cuentas registradas.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('143','Número de préstamos abiertos.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('144','Número de cuentas recientemente aperturadas de crédito al consume.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('145','Número de cuentas departamentales.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('146','Número de cuentas departamentales con saldo.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('147','Número de cuentas revolventes.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('148','Número de cuentas revolventes con saldo mayor a límite de crédito.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('160','Proporción del saldo con relación al límite en crédito automotriz es alta.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('161','Proporción del saldo con relación al límite de crédito en cuentas con morosidad es alto.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('162','Proporción del saldo con relación al límite en cuentas de crédito al consumo es alto.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('163','Proporción del saldo con relación al límite en cuentas departamentales es alto.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('166','Proporción del saldo con relación al límite en cuentas revolventes es alto.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('167','Proporción del saldo con relación al límite en cuentas de ventas a crédito es alto.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('168','Proporción de saldos de préstamos sobre préstamos hipotecarios es alto.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('169','Proporción de saldos de préstamos con relación A los montos originales es alto.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('170','Proporción de saldos de créditos revolventes con relación al total del saldo es alto.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('180','Pocas cuentas con pago al corriente.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('181','Pocas cuentas con saldo. ')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('182','Pocas cuentas con información reciente de pagos.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('183','Pocas cuentas activas.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('186','Pocas cuentas crédito al consumo con información reciente de pagos.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('187','Pocas cuentas con préstamos.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('188','Pocas cuentas departamentales.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('189','Pocas cuentas departamentales con información reciente de pagos.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('190','Pocas cuentas revolventes.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('191','Pocas cuentas revolventes con información reciente de pagos.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('192','Pocas cuentas de ventas a crédito coAAinformación reciente de pagos.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('200','Demasiadas cuentas recientemente aperturadas.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('201','Demasiadas cuentas con saldo.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('203','Demasiadas cuentas de crédito al consumo.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('204','Demasiadas cuentas con préstamo.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('205','Demasiadas consultas recientes.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('206','Demasiadas cuentas con actividad reciente.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('207','Demasiadas cuentas automotrices con actividad reciente.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('209','Demasiadas cuentas de crédito al consumo con actividad reciente.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('210','Demasiadas cuentas con préstamo con actividad reciente.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('211','Demasiadas cuentas departamentales con actividad reciente.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('214','Demasiadas cuentas de reciente apertura con saldos.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('216','Demasiadas cuentas de crédito al consumo de reciente apertura.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('217','Demasiadas cuentas con préstamo de reciente apertura.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('218','Demasiadas cuentas departamentales de reciente apertura con saldos.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('219','Demasiadas cuentas revolventes de reciente apertura.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('220','Demasiadas cuentas revolventes de reciente apertura con saldos.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('221','Demasiadas cuentas de ventas a crédito de reciente apertura. ')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('222','Demasiadas cuentas departamentales.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('223','Demasiadas cuentas revolventes.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('234','Cuenta con cargo a tarjeta con poca información.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('235','No hay saldos por cargos recientes a tarjeta.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('236','Proporción de saldos a límites de crédito en cuentas con cargos a tarjeta es alto.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('240','Cuentas con pagos vencidos.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('260','El Informe Buró presenta acciones legales.') 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('261','Acción legal en el Informe Buró es reciente.')
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion)
VALUES ('262','El Informe Buró presenta asuntos legales sin concluir')

INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion,EsRazon,EsExclusion)
VALUES ('-002','Expediente no tiene al menos una cuenta con antigüedad mínima de 6 meses.',0,1) 
INSERT INTO dbo.tBURcatalogosCodigosIndiceCapacidadCrediticiaICC(Codigo,Descripcion,EsRazon,EsExclusion)
VALUES ('-003','Expediente no cuenta con BC Score.',0,1) 


SELECT * FROM tBURcatalogosCodigosIndiceCapacidadCrediticiaICC

