


IF EXISTS(SELECT name FROM sys.objects o WHERE o.name='vOBJECTS')
BEGIN
	DROP VIEW vOBJECTS
	SELECT 'vOBJECTS BORRADO' AS info
END
GO

CREATE VIEW [dbo].[vOBJECTS]
	AS
SELECT	
	SM.OBJECT_ID,
	NAME = OBJECT_NAME(SM.OBJECT_ID),
	DEFINITION  = SM.DEFINITION,
	TYPE		= SO.TYPE,
	TYPE_DESC	= SO.TYPE_DESC,	
	ALTA		= SO.CREATE_DATE,
	CAMBIO		= SO.MODIFY_DATE
FROM SYS.SQL_MODULES	AS SM
INNER JOIN SYS.OBJECTS	AS SO ON SM.OBJECT_ID = SO.OBJECT_ID 

GO




