


IF NOT EXISTS(SELECT name FROM sys.tables WHERE name='tASEMEXestados')
BEGIN
	CREATE TABLE [dbo].[tASEMEXestados]
	(
		IdEstado			INT FOREIGN KEY REFERENCES dbo.tCTLestados(IdEstado),
		PKEstado			INT UNIQUE,
		NomEstado			VARCHAR(80),
		IdEstatus 			INT NOT NULL DEFAULT 1
	) ON [PRIMARY]
	SELECT 'Tabla Creada tASEMEXestados' AS info
	
	ALTER TABLE dbo.tASEMEXestados 
	ADD CONSTRAINT FK_tASEMEXestados_IdEstatus 
	FOREIGN KEY (IdEstatus) REFERENCES dbo.tCTLestatus (IdEstatus)
	
END
ELSE 
	-- DROP TABLE tASEMEXestados
	SELECT 'tASEMEXestados Existe'
GO



INSERT INTO dbo.tASEMEXestados (IdEstado,PKEstado,NomEstado)
SELECT 1, 1, 'AGUASCALIENTES'
UNION
SELECT 2, 2, 'BAJA CALIFORNIA'
UNION
SELECT 3, 3, 'BAJA CALIFORNIA SUR'
UNION
SELECT 4, 4, 'CAMPECHE'
UNION
SELECT 7, 5, 'COAHUILA'
UNION
SELECT 8, 6, 'COLIMA'
UNION
SELECT 5, 7, 'CHIAPAS'
UNION
SELECT 6, 8, 'CHIHUAHUA'
UNION
SELECT 9, 9, 'DISTRITO FEDERAL'
UNION
SELECT 10, 10, 'DURANGO'
UNION
SELECT 12, 11, 'GUANAJUATO'
UNION
SELECT 13, 12, 'GUERRERO'
UNION
SELECT 14, 13, 'HIDALGO'
UNION
SELECT 15, 14, 'JALISCO'
UNION
SELECT 11, 15, 'ESTADO DE MEXICO'
UNION
SELECT 16, 16, 'MICHOACAN'
UNION
SELECT 17, 17, 'MORELOS'
UNION
SELECT 18, 18, 'NAYARIT'
UNION
SELECT 19, 19, 'NUEVO LEON'
UNION
SELECT 20, 20, 'OAXACA'
UNION
SELECT 21, 21, 'PUEBLA'
UNION
SELECT 22, 22, 'QUERETARO'
UNION
SELECT 23, 23, 'QUINTANA ROO'
UNION
SELECT 24, 24, 'SAN LUIS POTOSI'
UNION
SELECT 25, 25, 'SINALOA'
UNION
SELECT 26, 26, 'SONORA'
UNION
SELECT 27, 27, 'TABASCO'
UNION
SELECT 28, 28, 'TAMAULIPAS'
UNION
SELECT 29, 29, 'TLAXCALA'
UNION
SELECT 30, 30, 'VERACRUZ'
UNION
SELECT 31, 31, 'YUCATAN'
UNION
SELECT 32, 32, 'ZACATECAS'

GO


